[project]
name = "agent-orchestration"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "langchain-core>=1.5.1",
    "langgraph>=1.2.9",
    "langgraph-checkpoint-sqlite>=3.1.0",
    "openai>=2.48.0",
    "python-dotenv>=1.2.2",
    "tiktoken>=0.13.0",
]
